/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  Analytics,
  Department,
  DepartmentCreate,
  GetDepartmentsParams,
  GetToolsParams,
  GetUserToolsParams,
  GetUsersParams,
  Tool,
  ToolCreate,
  User,
  UserCreate,
  UserTool,
} from '../model'

import { customFetcher } from '../../lib/fetcher'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getDepartmentsResponse200 = {
  data: Department[]
  status: 200
}

export type getDepartmentsResponseSuccess = getDepartmentsResponse200 & {
  headers: Headers
}
export type getDepartmentsResponse = getDepartmentsResponseSuccess

export const getGetDepartmentsUrl = (params?: GetDepartmentsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/departments?${stringifiedParams}`
    : `/departments`
}

/**
 * @summary List departments
 */
export const getDepartments = async (
  params?: GetDepartmentsParams,
  options?: RequestInit,
): Promise<getDepartmentsResponse> => {
  return customFetcher<getDepartmentsResponse>(getGetDepartmentsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetDepartmentsQueryKey = (params?: GetDepartmentsParams) => {
  return [`/departments`, ...(params ? [params] : [])] as const
}

export const getGetDepartmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDepartments>>,
  TError = unknown,
>(
  params?: GetDepartmentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDepartmentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartments>>> = ({
    signal,
  }) => getDepartments(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDepartments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDepartments>>
>
export type GetDepartmentsQueryError = unknown

export function useGetDepartments<
  TData = Awaited<ReturnType<typeof getDepartments>>,
  TError = unknown,
>(
  params: undefined | GetDepartmentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartments>>,
          TError,
          Awaited<ReturnType<typeof getDepartments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDepartments<
  TData = Awaited<ReturnType<typeof getDepartments>>,
  TError = unknown,
>(
  params?: GetDepartmentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartments>>,
          TError,
          Awaited<ReturnType<typeof getDepartments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDepartments<
  TData = Awaited<ReturnType<typeof getDepartments>>,
  TError = unknown,
>(
  params?: GetDepartmentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List departments
 */

export function useGetDepartments<
  TData = Awaited<ReturnType<typeof getDepartments>>,
  TError = unknown,
>(
  params?: GetDepartmentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetDepartmentsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postDepartmentsResponse201 = {
  data: void
  status: 201
}

export type postDepartmentsResponseSuccess = postDepartmentsResponse201 & {
  headers: Headers
}
export type postDepartmentsResponse = postDepartmentsResponseSuccess

export const getPostDepartmentsUrl = () => {
  return `/departments`
}

/**
 * @summary Create department
 */
export const postDepartments = async (
  departmentCreate: DepartmentCreate,
  options?: RequestInit,
): Promise<postDepartmentsResponse> => {
  return customFetcher<postDepartmentsResponse>(getPostDepartmentsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(departmentCreate),
  })
}

export const getPostDepartmentsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDepartments>>,
    TError,
    { data: DepartmentCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDepartments>>,
  TError,
  { data: DepartmentCreate },
  TContext
> => {
  const mutationKey = ['postDepartments']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDepartments>>,
    { data: DepartmentCreate }
  > = (props) => {
    const { data } = props ?? {}

    return postDepartments(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostDepartmentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDepartments>>
>
export type PostDepartmentsMutationBody = DepartmentCreate
export type PostDepartmentsMutationError = unknown

/**
 * @summary Create department
 */
export const usePostDepartments = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDepartments>>,
      TError,
      { data: DepartmentCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDepartments>>,
  TError,
  { data: DepartmentCreate },
  TContext
> => {
  return useMutation(getPostDepartmentsMutationOptions(options), queryClient)
}
export type getDepartmentsIdResponse200 = {
  data: Department
  status: 200
}

export type getDepartmentsIdResponseSuccess = getDepartmentsIdResponse200 & {
  headers: Headers
}
export type getDepartmentsIdResponse = getDepartmentsIdResponseSuccess

export const getGetDepartmentsIdUrl = (id: number) => {
  return `/departments/${id}`
}

/**
 * @summary Get department by id
 */
export const getDepartmentsId = async (
  id: number,
  options?: RequestInit,
): Promise<getDepartmentsIdResponse> => {
  return customFetcher<getDepartmentsIdResponse>(getGetDepartmentsIdUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetDepartmentsIdQueryKey = (id: number) => {
  return [`/departments/${id}`] as const
}

export const getGetDepartmentsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDepartmentsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDepartmentsId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDepartmentsIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDepartmentsId>>
  > = ({ signal }) => getDepartmentsId(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDepartmentsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDepartmentsId>>
>
export type GetDepartmentsIdQueryError = unknown

export function useGetDepartmentsId<
  TData = Awaited<ReturnType<typeof getDepartmentsId>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDepartmentsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentsId>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentsId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDepartmentsId<
  TData = Awaited<ReturnType<typeof getDepartmentsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDepartmentsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentsId>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentsId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDepartmentsId<
  TData = Awaited<ReturnType<typeof getDepartmentsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDepartmentsId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get department by id
 */

export function useGetDepartmentsId<
  TData = Awaited<ReturnType<typeof getDepartmentsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDepartmentsId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetDepartmentsIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type putDepartmentsIdResponse200 = {
  data: void
  status: 200
}

export type putDepartmentsIdResponseSuccess = putDepartmentsIdResponse200 & {
  headers: Headers
}
export type putDepartmentsIdResponse = putDepartmentsIdResponseSuccess

export const getPutDepartmentsIdUrl = (id: number) => {
  return `/departments/${id}`
}

/**
 * @summary Update department
 */
export const putDepartmentsId = async (
  id: number,
  departmentCreate: DepartmentCreate,
  options?: RequestInit,
): Promise<putDepartmentsIdResponse> => {
  return customFetcher<putDepartmentsIdResponse>(getPutDepartmentsIdUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(departmentCreate),
  })
}

export const getPutDepartmentsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putDepartmentsId>>,
    TError,
    { id: number; data: DepartmentCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof putDepartmentsId>>,
  TError,
  { id: number; data: DepartmentCreate },
  TContext
> => {
  const mutationKey = ['putDepartmentsId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putDepartmentsId>>,
    { id: number; data: DepartmentCreate }
  > = (props) => {
    const { id, data } = props ?? {}

    return putDepartmentsId(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutDepartmentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putDepartmentsId>>
>
export type PutDepartmentsIdMutationBody = DepartmentCreate
export type PutDepartmentsIdMutationError = unknown

/**
 * @summary Update department
 */
export const usePutDepartmentsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putDepartmentsId>>,
      TError,
      { id: number; data: DepartmentCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putDepartmentsId>>,
  TError,
  { id: number; data: DepartmentCreate },
  TContext
> => {
  return useMutation(getPutDepartmentsIdMutationOptions(options), queryClient)
}
export type deleteDepartmentsIdResponse204 = {
  data: void
  status: 204
}

export type deleteDepartmentsIdResponseSuccess =
  deleteDepartmentsIdResponse204 & {
    headers: Headers
  }
export type deleteDepartmentsIdResponse = deleteDepartmentsIdResponseSuccess

export const getDeleteDepartmentsIdUrl = (id: number) => {
  return `/departments/${id}`
}

/**
 * @summary Delete department
 */
export const deleteDepartmentsId = async (
  id: number,
  options?: RequestInit,
): Promise<deleteDepartmentsIdResponse> => {
  return customFetcher<deleteDepartmentsIdResponse>(
    getDeleteDepartmentsIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    },
  )
}

export const getDeleteDepartmentsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDepartmentsId>>,
    TError,
    { id: number },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDepartmentsId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteDepartmentsId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDepartmentsId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {}

    return deleteDepartmentsId(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteDepartmentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDepartmentsId>>
>

export type DeleteDepartmentsIdMutationError = unknown

/**
 * @summary Delete department
 */
export const useDeleteDepartmentsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDepartmentsId>>,
      TError,
      { id: number },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDepartmentsId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDeleteDepartmentsIdMutationOptions(options),
    queryClient,
  )
}
export type getUsersResponse200 = {
  data: User[]
  status: 200
}

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers
}
export type getUsersResponse = getUsersResponseSuccess

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

/**
 * @summary List users
 */
export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customFetcher<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetUsersQueryKey = (params?: GetUsersParams) => {
  return [`/users`, ...(params ? [params] : [])] as const
}

export const getGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>
export type GetUsersQueryError = unknown

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: undefined | GetUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List users
 */

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUsersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postUsersResponse201 = {
  data: void
  status: 201
}

export type postUsersResponseSuccess = postUsersResponse201 & {
  headers: Headers
}
export type postUsersResponse = postUsersResponseSuccess

export const getPostUsersUrl = () => {
  return `/users`
}

/**
 * @summary Create user
 */
export const postUsers = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<postUsersResponse> => {
  return customFetcher<postUsersResponse>(getPostUsersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreate),
  })
}

export const getPostUsersMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUsers>>,
    TError,
    { data: UserCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUsers>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ['postUsers']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUsers>>,
    { data: UserCreate }
  > = (props) => {
    const { data } = props ?? {}

    return postUsers(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUsers>>
>
export type PostUsersMutationBody = UserCreate
export type PostUsersMutationError = unknown

/**
 * @summary Create user
 */
export const usePostUsers = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUsers>>,
      TError,
      { data: UserCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUsers>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  return useMutation(getPostUsersMutationOptions(options), queryClient)
}
export type getUsersIdResponse200 = {
  data: User
  status: 200
}

export type getUsersIdResponseSuccess = getUsersIdResponse200 & {
  headers: Headers
}
export type getUsersIdResponse = getUsersIdResponseSuccess

export const getGetUsersIdUrl = (id: number) => {
  return `/users/${id}`
}

/**
 * @summary Get user by id
 */
export const getUsersId = async (
  id: number,
  options?: RequestInit,
): Promise<getUsersIdResponse> => {
  return customFetcher<getUsersIdResponse>(getGetUsersIdUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetUsersIdQueryKey = (id: number) => {
  return [`/users/${id}`] as const
}

export const getGetUsersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersId>>> = ({
    signal,
  }) => getUsersId(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersId>>
>
export type GetUsersIdQueryError = unknown

export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get user by id
 */

export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUsersIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type putUsersIdResponse200 = {
  data: void
  status: 200
}

export type putUsersIdResponseSuccess = putUsersIdResponse200 & {
  headers: Headers
}
export type putUsersIdResponse = putUsersIdResponseSuccess

export const getPutUsersIdUrl = (id: number) => {
  return `/users/${id}`
}

/**
 * @summary Update user
 */
export const putUsersId = async (
  id: number,
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<putUsersIdResponse> => {
  return customFetcher<putUsersIdResponse>(getPutUsersIdUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreate),
  })
}

export const getPutUsersIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putUsersId>>,
    TError,
    { id: number; data: UserCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof putUsersId>>,
  TError,
  { id: number; data: UserCreate },
  TContext
> => {
  const mutationKey = ['putUsersId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putUsersId>>,
    { id: number; data: UserCreate }
  > = (props) => {
    const { id, data } = props ?? {}

    return putUsersId(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutUsersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putUsersId>>
>
export type PutUsersIdMutationBody = UserCreate
export type PutUsersIdMutationError = unknown

/**
 * @summary Update user
 */
export const usePutUsersId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putUsersId>>,
      TError,
      { id: number; data: UserCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putUsersId>>,
  TError,
  { id: number; data: UserCreate },
  TContext
> => {
  return useMutation(getPutUsersIdMutationOptions(options), queryClient)
}
export type deleteUsersIdResponse204 = {
  data: void
  status: 204
}

export type deleteUsersIdResponseSuccess = deleteUsersIdResponse204 & {
  headers: Headers
}
export type deleteUsersIdResponse = deleteUsersIdResponseSuccess

export const getDeleteUsersIdUrl = (id: number) => {
  return `/users/${id}`
}

/**
 * @summary Delete user
 */
export const deleteUsersId = async (
  id: number,
  options?: RequestInit,
): Promise<deleteUsersIdResponse> => {
  return customFetcher<deleteUsersIdResponse>(getDeleteUsersIdUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteUsersIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUsersId>>,
    TError,
    { id: number },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUsersId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteUsersId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUsersId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {}

    return deleteUsersId(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteUsersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUsersId>>
>

export type DeleteUsersIdMutationError = unknown

/**
 * @summary Delete user
 */
export const useDeleteUsersId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUsersId>>,
      TError,
      { id: number },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUsersId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteUsersIdMutationOptions(options), queryClient)
}
export type getToolsResponse200 = {
  data: Tool[]
  status: 200
}

export type getToolsResponseSuccess = getToolsResponse200 & {
  headers: Headers
}
export type getToolsResponse = getToolsResponseSuccess

export const getGetToolsUrl = (params?: GetToolsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/tools?${stringifiedParams}` : `/tools`
}

/**
 * @summary List tools
 */
export const getTools = async (
  params?: GetToolsParams,
  options?: RequestInit,
): Promise<getToolsResponse> => {
  return customFetcher<getToolsResponse>(getGetToolsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetToolsQueryKey = (params?: GetToolsParams) => {
  return [`/tools`, ...(params ? [params] : [])] as const
}

export const getGetToolsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTools>>,
  TError = unknown,
>(
  params?: GetToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetToolsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTools>>> = ({
    signal,
  }) => getTools(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTools>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetToolsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTools>>
>
export type GetToolsQueryError = unknown

export function useGetTools<
  TData = Awaited<ReturnType<typeof getTools>>,
  TError = unknown,
>(
  params: undefined | GetToolsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTools>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTools>>,
          TError,
          Awaited<ReturnType<typeof getTools>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTools<
  TData = Awaited<ReturnType<typeof getTools>>,
  TError = unknown,
>(
  params?: GetToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTools>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTools>>,
          TError,
          Awaited<ReturnType<typeof getTools>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTools<
  TData = Awaited<ReturnType<typeof getTools>>,
  TError = unknown,
>(
  params?: GetToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List tools
 */

export function useGetTools<
  TData = Awaited<ReturnType<typeof getTools>>,
  TError = unknown,
>(
  params?: GetToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetToolsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postToolsResponse201 = {
  data: void
  status: 201
}

export type postToolsResponseSuccess = postToolsResponse201 & {
  headers: Headers
}
export type postToolsResponse = postToolsResponseSuccess

export const getPostToolsUrl = () => {
  return `/tools`
}

/**
 * @summary Create tool
 */
export const postTools = async (
  toolCreate: ToolCreate,
  options?: RequestInit,
): Promise<postToolsResponse> => {
  return customFetcher<postToolsResponse>(getPostToolsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(toolCreate),
  })
}

export const getPostToolsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTools>>,
    TError,
    { data: ToolCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTools>>,
  TError,
  { data: ToolCreate },
  TContext
> => {
  const mutationKey = ['postTools']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTools>>,
    { data: ToolCreate }
  > = (props) => {
    const { data } = props ?? {}

    return postTools(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostToolsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTools>>
>
export type PostToolsMutationBody = ToolCreate
export type PostToolsMutationError = unknown

/**
 * @summary Create tool
 */
export const usePostTools = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTools>>,
      TError,
      { data: ToolCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTools>>,
  TError,
  { data: ToolCreate },
  TContext
> => {
  return useMutation(getPostToolsMutationOptions(options), queryClient)
}
export type getToolsIdResponse200 = {
  data: Tool
  status: 200
}

export type getToolsIdResponseSuccess = getToolsIdResponse200 & {
  headers: Headers
}
export type getToolsIdResponse = getToolsIdResponseSuccess

export const getGetToolsIdUrl = (id: number) => {
  return `/tools/${id}`
}

/**
 * @summary Get tool by id
 */
export const getToolsId = async (
  id: number,
  options?: RequestInit,
): Promise<getToolsIdResponse> => {
  return customFetcher<getToolsIdResponse>(getGetToolsIdUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetToolsIdQueryKey = (id: number) => {
  return [`/tools/${id}`] as const
}

export const getGetToolsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getToolsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getToolsId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetToolsIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getToolsId>>> = ({
    signal,
  }) => getToolsId(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getToolsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetToolsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getToolsId>>
>
export type GetToolsIdQueryError = unknown

export function useGetToolsId<
  TData = Awaited<ReturnType<typeof getToolsId>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getToolsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getToolsId>>,
          TError,
          Awaited<ReturnType<typeof getToolsId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetToolsId<
  TData = Awaited<ReturnType<typeof getToolsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getToolsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getToolsId>>,
          TError,
          Awaited<ReturnType<typeof getToolsId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetToolsId<
  TData = Awaited<ReturnType<typeof getToolsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getToolsId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get tool by id
 */

export function useGetToolsId<
  TData = Awaited<ReturnType<typeof getToolsId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getToolsId>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetToolsIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type putToolsIdResponse200 = {
  data: void
  status: 200
}

export type putToolsIdResponseSuccess = putToolsIdResponse200 & {
  headers: Headers
}
export type putToolsIdResponse = putToolsIdResponseSuccess

export const getPutToolsIdUrl = (id: number) => {
  return `/tools/${id}`
}

/**
 * @summary Update tool
 */
export const putToolsId = async (
  id: number,
  toolCreate: ToolCreate,
  options?: RequestInit,
): Promise<putToolsIdResponse> => {
  return customFetcher<putToolsIdResponse>(getPutToolsIdUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(toolCreate),
  })
}

export const getPutToolsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putToolsId>>,
    TError,
    { id: number; data: ToolCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof putToolsId>>,
  TError,
  { id: number; data: ToolCreate },
  TContext
> => {
  const mutationKey = ['putToolsId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putToolsId>>,
    { id: number; data: ToolCreate }
  > = (props) => {
    const { id, data } = props ?? {}

    return putToolsId(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutToolsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putToolsId>>
>
export type PutToolsIdMutationBody = ToolCreate
export type PutToolsIdMutationError = unknown

/**
 * @summary Update tool
 */
export const usePutToolsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putToolsId>>,
      TError,
      { id: number; data: ToolCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putToolsId>>,
  TError,
  { id: number; data: ToolCreate },
  TContext
> => {
  return useMutation(getPutToolsIdMutationOptions(options), queryClient)
}
export type deleteToolsIdResponse204 = {
  data: void
  status: 204
}

export type deleteToolsIdResponseSuccess = deleteToolsIdResponse204 & {
  headers: Headers
}
export type deleteToolsIdResponse = deleteToolsIdResponseSuccess

export const getDeleteToolsIdUrl = (id: number) => {
  return `/tools/${id}`
}

/**
 * @summary Delete tool
 */
export const deleteToolsId = async (
  id: number,
  options?: RequestInit,
): Promise<deleteToolsIdResponse> => {
  return customFetcher<deleteToolsIdResponse>(getDeleteToolsIdUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteToolsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteToolsId>>,
    TError,
    { id: number },
    TContext
  >
  request?: SecondParameter<typeof customFetcher>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteToolsId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteToolsId']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteToolsId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {}

    return deleteToolsId(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteToolsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteToolsId>>
>

export type DeleteToolsIdMutationError = unknown

/**
 * @summary Delete tool
 */
export const useDeleteToolsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteToolsId>>,
      TError,
      { id: number },
      TContext
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteToolsId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteToolsIdMutationOptions(options), queryClient)
}
export type getUserToolsResponse200 = {
  data: UserTool[]
  status: 200
}

export type getUserToolsResponseSuccess = getUserToolsResponse200 & {
  headers: Headers
}
export type getUserToolsResponse = getUserToolsResponseSuccess

export const getGetUserToolsUrl = (params?: GetUserToolsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/user_tools?${stringifiedParams}`
    : `/user_tools`
}

/**
 * @summary List user_tool relations
 */
export const getUserTools = async (
  params?: GetUserToolsParams,
  options?: RequestInit,
): Promise<getUserToolsResponse> => {
  return customFetcher<getUserToolsResponse>(getGetUserToolsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetUserToolsQueryKey = (params?: GetUserToolsParams) => {
  return [`/user_tools`, ...(params ? [params] : [])] as const
}

export const getGetUserToolsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserTools>>,
  TError = unknown,
>(
  params?: GetUserToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserToolsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserTools>>> = ({
    signal,
  }) => getUserTools(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserTools>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserToolsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserTools>>
>
export type GetUserToolsQueryError = unknown

export function useGetUserTools<
  TData = Awaited<ReturnType<typeof getUserTools>>,
  TError = unknown,
>(
  params: undefined | GetUserToolsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTools>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTools>>,
          TError,
          Awaited<ReturnType<typeof getUserTools>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserTools<
  TData = Awaited<ReturnType<typeof getUserTools>>,
  TError = unknown,
>(
  params?: GetUserToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTools>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTools>>,
          TError,
          Awaited<ReturnType<typeof getUserTools>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserTools<
  TData = Awaited<ReturnType<typeof getUserTools>>,
  TError = unknown,
>(
  params?: GetUserToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List user_tool relations
 */

export function useGetUserTools<
  TData = Awaited<ReturnType<typeof getUserTools>>,
  TError = unknown,
>(
  params?: GetUserToolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTools>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserToolsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getAnalyticsResponse200 = {
  data: Analytics
  status: 200
}

export type getAnalyticsResponseSuccess = getAnalyticsResponse200 & {
  headers: Headers
}
export type getAnalyticsResponse = getAnalyticsResponseSuccess

export const getGetAnalyticsUrl = () => {
  return `/analytics`
}

/**
 * @summary Analytics and KPIs
 */
export const getAnalytics = async (
  options?: RequestInit,
): Promise<getAnalyticsResponse> => {
  return customFetcher<getAnalyticsResponse>(getGetAnalyticsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetAnalyticsQueryKey = () => {
  return [`/analytics`] as const
}

export const getGetAnalyticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnalytics>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetcher>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAnalyticsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalytics>>> = ({
    signal,
  }) => getAnalytics({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAnalytics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnalytics>>
>
export type GetAnalyticsQueryError = unknown

export function useGetAnalytics<
  TData = Awaited<ReturnType<typeof getAnalytics>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getAnalytics>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAnalytics<
  TData = Awaited<ReturnType<typeof getAnalytics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getAnalytics>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAnalytics<
  TData = Awaited<ReturnType<typeof getAnalytics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Analytics and KPIs
 */

export function useGetAnalytics<
  TData = Awaited<ReturnType<typeof getAnalytics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetcher>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAnalyticsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
