/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker'

import type { RequestHandlerOptions } from 'msw'
import { HttpResponse, http } from 'msw'

import type { Analytics, Department, Tool, User, UserTool } from '../model'

export const getGetDepartmentsResponseMock = (): Department[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
  }))

export const getGetDepartmentsIdResponseMock = (
  overrideResponse: Partial<Extract<Department, object>> = {},
): Department => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    undefined,
  ]),
  ...overrideResponse,
})

export const getGetUsersResponseMock = (): User[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.internet.email(),
    department_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    role: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    joined_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 10),
      undefined,
    ]),
  }))

export const getGetUsersIdResponseMock = (
  overrideResponse: Partial<Extract<User, object>> = {},
): User => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  department_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
  role: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  joined_at: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 10),
    undefined,
  ]),
  ...overrideResponse,
})

export const getGetToolsResponseMock = (): Tool[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    vendor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    category: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    monthly_cost: faker.helpers.arrayElement([
      faker.number.float({ fractionDigits: 2 }),
      undefined,
    ]),
    previous_month_cost: faker.helpers.arrayElement([
      faker.number.float({ fractionDigits: 2 }),
      undefined,
    ]),
    owner_department: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    status: faker.helpers.arrayElement([
      'active',
      'unused',
      'expiring',
    ] as const),
    website_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    active_users_count: faker.helpers.arrayElement([
      faker.number.int(),
      undefined,
    ]),
    icon_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
  }))

export const getGetToolsIdResponseMock = (
  overrideResponse: Partial<Extract<Tool, object>> = {},
): Tool => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  vendor: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  category: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  monthly_cost: faker.helpers.arrayElement([
    faker.number.float({ fractionDigits: 2 }),
    undefined,
  ]),
  previous_month_cost: faker.helpers.arrayElement([
    faker.number.float({ fractionDigits: 2 }),
    undefined,
  ]),
  owner_department: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  status: faker.helpers.arrayElement(['active', 'unused', 'expiring'] as const),
  website_url: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  active_users_count: faker.helpers.arrayElement([
    faker.number.int(),
    undefined,
  ]),
  icon_url: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    undefined,
  ]),
  ...overrideResponse,
})

export const getGetUserToolsResponseMock = (): UserTool[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    tool_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    usage_frequency: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        'daily',
        'weekly',
        'monthly',
        'rarely',
      ] as const),
      undefined,
    ]),
    last_used: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
    proficiency_level: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        'beginner',
        'intermediate',
        'advanced',
        'expert',
      ] as const),
      undefined,
    ]),
  }))

export const getGetAnalyticsResponseMock = (
  overrideResponse: Partial<Extract<Analytics, object>> = {},
): Analytics => ({
  budget_overview: faker.helpers.arrayElement([{}, undefined]),
  kpi_trends: faker.helpers.arrayElement([{}, undefined]),
  cost_analytics: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getGetDepartmentsMockHandler = (
  overrideResponse?:
    | Department[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Department[]> | Department[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/departments',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDepartmentsResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPostDepartmentsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/departments',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 201 })
    },
    options,
  )
}

export const getGetDepartmentsIdMockHandler = (
  overrideResponse?:
    | Department
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Department> | Department),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/departments/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDepartmentsIdResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPutDepartmentsIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/departments/:id',
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getDeleteDepartmentsIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/departments/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getGetUsersMockHandler = (
  overrideResponse?:
    | User[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<User[]> | User[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/users',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPostUsersMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/users',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 201 })
    },
    options,
  )
}

export const getGetUsersIdMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/users/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersIdResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPutUsersIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/users/:id',
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getDeleteUsersIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/users/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getGetToolsMockHandler = (
  overrideResponse?:
    | Tool[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Tool[]> | Tool[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/tools',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetToolsResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPostToolsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/tools',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 201 })
    },
    options,
  )
}

export const getGetToolsIdMockHandler = (
  overrideResponse?:
    | Tool
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Tool> | Tool),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/tools/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetToolsIdResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPutToolsIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/tools/:id',
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getDeleteToolsIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/tools/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getGetUserToolsMockHandler = (
  overrideResponse?:
    | UserTool[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserTool[]> | UserTool[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/user_tools',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUserToolsResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getGetAnalyticsMockHandler = (
  overrideResponse?:
    | Analytics
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Analytics> | Analytics),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/analytics',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAnalyticsResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}
export const getDefaultMock = () => [
  getGetDepartmentsMockHandler(),
  getPostDepartmentsMockHandler(),
  getGetDepartmentsIdMockHandler(),
  getPutDepartmentsIdMockHandler(),
  getDeleteDepartmentsIdMockHandler(),
  getGetUsersMockHandler(),
  getPostUsersMockHandler(),
  getGetUsersIdMockHandler(),
  getPutUsersIdMockHandler(),
  getDeleteUsersIdMockHandler(),
  getGetToolsMockHandler(),
  getPostToolsMockHandler(),
  getGetToolsIdMockHandler(),
  getPutToolsIdMockHandler(),
  getDeleteToolsIdMockHandler(),
  getGetUserToolsMockHandler(),
  getGetAnalyticsMockHandler(),
]
