/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type { AnalyticsBudgetOverview } from './analyticsBudgetOverview.ts'
import type { AnalyticsCostAnalytics } from './analyticsCostAnalytics.ts'
import type { AnalyticsKpiTrends } from './analyticsKpiTrends.ts'

export interface Analytics {
  budget_overview?: AnalyticsBudgetOverview
  kpi_trends?: AnalyticsKpiTrends
  cost_analytics?: AnalyticsCostAnalytics
}
