/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export interface Department {
  id: number
  name: string
  description?: string
  created_at?: string
  updated_at?: string
}
