/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export type GetToolsStatus =
  (typeof GetToolsStatus)[keyof typeof GetToolsStatus]

export const GetToolsStatus = {
  active: 'active',
  unused: 'unused',
  expiring: 'expiring',
} as const
