/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type { GetToolsStatus } from './getToolsStatus.ts'
import type { LimitParameter } from './limitParameter.ts'
import type { OrderParameter } from './orderParameter.ts'
import type { PageParameter } from './pageParameter.ts'
import type { SortParameter } from './sortParameter.ts'

export type GetToolsParams = {
  /**
   * Page number (json-server style)
   */
  _page?: PageParameter
  /**
   * Page size
   */
  _limit?: LimitParameter
  /**
   * Field to sort by
   */
  _sort?: SortParameter
  /**
   * Sort order
   */
  _order?: OrderParameter
  status?: GetToolsStatus
  name_like?: string
}
