/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type { LimitParameter } from './limitParameter.ts'
import type { PageParameter } from './pageParameter.ts'

export type GetUserToolsParams = {
  /**
   * Page number (json-server style)
   */
  _page?: PageParameter
  /**
   * Page size
   */
  _limit?: LimitParameter
  user_id?: number
  tool_id?: number
}
