/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export type OrderParameter =
  (typeof OrderParameter)[keyof typeof OrderParameter]

export const OrderParameter = {
  asc: 'asc',
  desc: 'desc',
} as const
