/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Page number (json-server style)
 */
export type PageParameter = number
