/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type { ToolStatus } from './toolStatus.ts'

export interface Tool {
  id: number
  name: string
  description?: string
  vendor?: string
  category?: string
  monthly_cost?: number
  previous_month_cost?: number
  owner_department?: string
  status: ToolStatus
  website_url?: string
  active_users_count?: number
  icon_url?: string
  created_at?: string
  updated_at?: string
}
