/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export type ToolStatus = (typeof ToolStatus)[keyof typeof ToolStatus]

export const ToolStatus = {
  active: 'active',
  unused: 'unused',
  expiring: 'expiring',
} as const
