/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export interface ToolCreate {
  name?: string
  description?: string
  vendor?: string
  category?: string
  monthly_cost?: number
  owner_department?: string
  status?: string
}
