/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export type UserToolUsageFrequency =
  (typeof UserToolUsageFrequency)[keyof typeof UserToolUsageFrequency]

export const UserToolUsageFrequency = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  rarely: 'rarely',
} as const
