/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: number
  name: string
  email: string
  department_id?: number
  role?: string
  active?: boolean
  joined_at?: string
}
