/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */
import type { UserToolProficiencyLevel } from './userToolProficiencyLevel.ts'
import type { UserToolUsageFrequency } from './userToolUsageFrequency.ts'

export interface UserTool {
  user_id?: number
  tool_id?: number
  usage_frequency?: UserToolUsageFrequency
  last_used?: string
  proficiency_level?: UserToolProficiencyLevel
}
