/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Alt Front JSON Server API
 * OpenAPI spec version: 1.0.0
 */

export type UserToolProficiencyLevel =
  (typeof UserToolProficiencyLevel)[keyof typeof UserToolProficiencyLevel]

export const UserToolProficiencyLevel = {
  beginner: 'beginner',
  intermediate: 'intermediate',
  advanced: 'advanced',
  expert: 'expert',
} as const
